version: '3.8'

services:
  web:
    build:
      context: .
      target: build
    container_name: photo-portfolio-dev
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true 